/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.pixability.model;

import org.apache.avro.specific.SpecificData;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public class Key extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = -4146142026100170945L;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"Key\",\"namespace\":\"com.pixability.model\",\"fields\":[{\"name\":\"line_item_id\",\"type\":\"long\"}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<Key> ENCODER =
      new BinaryMessageEncoder<Key>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<Key> DECODER =
      new BinaryMessageDecoder<Key>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   */
  public static BinaryMessageDecoder<Key> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   */
  public static BinaryMessageDecoder<Key> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<Key>(MODEL$, SCHEMA$, resolver);
  }

  /** Serializes this Key to a ByteBuffer. */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /** Deserializes a Key from a ByteBuffer. */
  public static Key fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

  @Deprecated public long line_item_id;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public Key() {}

  /**
   * All-args constructor.
   * @param line_item_id The new value for line_item_id
   */
  public Key(java.lang.Long line_item_id) {
    this.line_item_id = line_item_id;
  }

  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call.
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return line_item_id;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  // Used by DatumReader.  Applications should not call.
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: line_item_id = (java.lang.Long)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  /**
   * Gets the value of the 'line_item_id' field.
   * @return The value of the 'line_item_id' field.
   */
  public java.lang.Long getLineItemId() {
    return line_item_id;
  }

  /**
   * Sets the value of the 'line_item_id' field.
   * @param value the value to set.
   */
  public void setLineItemId(java.lang.Long value) {
    this.line_item_id = value;
  }

  /**
   * Creates a new Key RecordBuilder.
   * @return A new Key RecordBuilder
   */
  public static com.pixability.model.Key.Builder newBuilder() {
    return new com.pixability.model.Key.Builder();
  }

  /**
   * Creates a new Key RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new Key RecordBuilder
   */
  public static com.pixability.model.Key.Builder newBuilder(com.pixability.model.Key.Builder other) {
    return new com.pixability.model.Key.Builder(other);
  }

  /**
   * Creates a new Key RecordBuilder by copying an existing Key instance.
   * @param other The existing instance to copy.
   * @return A new Key RecordBuilder
   */
  public static com.pixability.model.Key.Builder newBuilder(com.pixability.model.Key other) {
    return new com.pixability.model.Key.Builder(other);
  }

  /**
   * RecordBuilder for Key instances.
   */
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<Key>
    implements org.apache.avro.data.RecordBuilder<Key> {

    private long line_item_id;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(com.pixability.model.Key.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.line_item_id)) {
        this.line_item_id = data().deepCopy(fields()[0].schema(), other.line_item_id);
        fieldSetFlags()[0] = true;
      }
    }

    /**
     * Creates a Builder by copying an existing Key instance
     * @param other The existing instance to copy.
     */
    private Builder(com.pixability.model.Key other) {
            super(SCHEMA$);
      if (isValidValue(fields()[0], other.line_item_id)) {
        this.line_item_id = data().deepCopy(fields()[0].schema(), other.line_item_id);
        fieldSetFlags()[0] = true;
      }
    }

    /**
      * Gets the value of the 'line_item_id' field.
      * @return The value.
      */
    public java.lang.Long getLineItemId() {
      return line_item_id;
    }

    /**
      * Sets the value of the 'line_item_id' field.
      * @param value The value of 'line_item_id'.
      * @return This builder.
      */
    public com.pixability.model.Key.Builder setLineItemId(long value) {
      validate(fields()[0], value);
      this.line_item_id = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'line_item_id' field has been set.
      * @return True if the 'line_item_id' field has been set, false otherwise.
      */
    public boolean hasLineItemId() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'line_item_id' field.
      * @return This builder.
      */
    public com.pixability.model.Key.Builder clearLineItemId() {
      fieldSetFlags()[0] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public Key build() {
      try {
        Key record = new Key();
        record.line_item_id = fieldSetFlags()[0] ? this.line_item_id : (java.lang.Long) defaultValue(fields()[0]);
        return record;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<Key>
    WRITER$ = (org.apache.avro.io.DatumWriter<Key>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<Key>
    READER$ = (org.apache.avro.io.DatumReader<Key>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

}
