/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.pixability.model;

import org.apache.avro.specific.SpecificData;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@SuppressWarnings("all")
/** InstaPot Line Item stats by platform and day / date */
@org.apache.avro.specific.AvroGenerated
public class LineItemPlatformSummaryDaily extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = 3351756354188327557L;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"LineItemPlatformSummaryDaily\",\"namespace\":\"com.pixability.model\",\"doc\":\"InstaPot Line Item stats by platform and day / date\",\"fields\":[{\"name\":\"platform\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"}},{\"name\":\"insertion_order_id\",\"type\":\"long\"},{\"name\":\"line_item_id\",\"type\":\"long\"},{\"name\":\"date\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"}},{\"name\":\"platform_clicks\",\"type\":[\"null\",\"long\"],\"default\":0},{\"name\":\"platform_impressions\",\"type\":[\"null\",\"long\"],\"default\":0},{\"name\":\"platform_spend\",\"type\":[\"null\",\"float\"],\"default\":0},{\"name\":\"platform_video_spend\",\"type\":[\"null\",\"float\"],\"default\":0},{\"name\":\"platform_video_views\",\"type\":[\"null\",\"long\"],\"default\":0},{\"name\":\"video_views_3_sec\",\"type\":[\"null\",\"long\"],\"default\":0},{\"name\":\"video_views_10_sec\",\"type\":[\"null\",\"long\"],\"default\":0},{\"name\":\"video_views_30_sec\",\"type\":[\"null\",\"long\"],\"default\":0},{\"name\":\"video_views_to_25_pct\",\"type\":[\"null\",\"long\"],\"default\":0},{\"name\":\"video_views_to_50_pct\",\"type\":[\"null\",\"long\"],\"default\":0},{\"name\":\"video_views_to_75_pct\",\"type\":[\"null\",\"long\"],\"default\":0},{\"name\":\"video_views_to_100_pct\",\"type\":[\"null\",\"long\"],\"default\":0},{\"name\":\"contract_clicks\",\"type\":[\"null\",\"long\"],\"default\":0},{\"name\":\"contract_impressions\",\"type\":[\"null\",\"long\"],\"default\":0},{\"name\":\"contract_spend\",\"type\":[\"null\",\"float\"],\"default\":0},{\"name\":\"contract_video_spend\",\"type\":[\"null\",\"float\"],\"default\":0},{\"name\":\"contract_video_views\",\"type\":[\"null\",\"long\"],\"default\":0}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<LineItemPlatformSummaryDaily> ENCODER =
      new BinaryMessageEncoder<LineItemPlatformSummaryDaily>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<LineItemPlatformSummaryDaily> DECODER =
      new BinaryMessageDecoder<LineItemPlatformSummaryDaily>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   */
  public static BinaryMessageDecoder<LineItemPlatformSummaryDaily> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   */
  public static BinaryMessageDecoder<LineItemPlatformSummaryDaily> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<LineItemPlatformSummaryDaily>(MODEL$, SCHEMA$, resolver);
  }

  /** Serializes this LineItemPlatformSummaryDaily to a ByteBuffer. */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /** Deserializes a LineItemPlatformSummaryDaily from a ByteBuffer. */
  public static LineItemPlatformSummaryDaily fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

  @Deprecated public java.lang.String platform;
  @Deprecated public long insertion_order_id;
  @Deprecated public long line_item_id;
  @Deprecated public java.lang.String date;
  @Deprecated public java.lang.Long platform_clicks;
  @Deprecated public java.lang.Long platform_impressions;
  @Deprecated public java.lang.Float platform_spend;
  @Deprecated public java.lang.Float platform_video_spend;
  @Deprecated public java.lang.Long platform_video_views;
  @Deprecated public java.lang.Long video_views_3_sec;
  @Deprecated public java.lang.Long video_views_10_sec;
  @Deprecated public java.lang.Long video_views_30_sec;
  @Deprecated public java.lang.Long video_views_to_25_pct;
  @Deprecated public java.lang.Long video_views_to_50_pct;
  @Deprecated public java.lang.Long video_views_to_75_pct;
  @Deprecated public java.lang.Long video_views_to_100_pct;
  @Deprecated public java.lang.Long contract_clicks;
  @Deprecated public java.lang.Long contract_impressions;
  @Deprecated public java.lang.Float contract_spend;
  @Deprecated public java.lang.Float contract_video_spend;
  @Deprecated public java.lang.Long contract_video_views;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public LineItemPlatformSummaryDaily() {}

  /**
   * All-args constructor.
   * @param platform The new value for platform
   * @param insertion_order_id The new value for insertion_order_id
   * @param line_item_id The new value for line_item_id
   * @param date The new value for date
   * @param platform_clicks The new value for platform_clicks
   * @param platform_impressions The new value for platform_impressions
   * @param platform_spend The new value for platform_spend
   * @param platform_video_spend The new value for platform_video_spend
   * @param platform_video_views The new value for platform_video_views
   * @param video_views_3_sec The new value for video_views_3_sec
   * @param video_views_10_sec The new value for video_views_10_sec
   * @param video_views_30_sec The new value for video_views_30_sec
   * @param video_views_to_25_pct The new value for video_views_to_25_pct
   * @param video_views_to_50_pct The new value for video_views_to_50_pct
   * @param video_views_to_75_pct The new value for video_views_to_75_pct
   * @param video_views_to_100_pct The new value for video_views_to_100_pct
   * @param contract_clicks The new value for contract_clicks
   * @param contract_impressions The new value for contract_impressions
   * @param contract_spend The new value for contract_spend
   * @param contract_video_spend The new value for contract_video_spend
   * @param contract_video_views The new value for contract_video_views
   */
  public LineItemPlatformSummaryDaily(java.lang.String platform, java.lang.Long insertion_order_id, java.lang.Long line_item_id, java.lang.String date, java.lang.Long platform_clicks, java.lang.Long platform_impressions, java.lang.Float platform_spend, java.lang.Float platform_video_spend, java.lang.Long platform_video_views, java.lang.Long video_views_3_sec, java.lang.Long video_views_10_sec, java.lang.Long video_views_30_sec, java.lang.Long video_views_to_25_pct, java.lang.Long video_views_to_50_pct, java.lang.Long video_views_to_75_pct, java.lang.Long video_views_to_100_pct, java.lang.Long contract_clicks, java.lang.Long contract_impressions, java.lang.Float contract_spend, java.lang.Float contract_video_spend, java.lang.Long contract_video_views) {
    this.platform = platform;
    this.insertion_order_id = insertion_order_id;
    this.line_item_id = line_item_id;
    this.date = date;
    this.platform_clicks = platform_clicks;
    this.platform_impressions = platform_impressions;
    this.platform_spend = platform_spend;
    this.platform_video_spend = platform_video_spend;
    this.platform_video_views = platform_video_views;
    this.video_views_3_sec = video_views_3_sec;
    this.video_views_10_sec = video_views_10_sec;
    this.video_views_30_sec = video_views_30_sec;
    this.video_views_to_25_pct = video_views_to_25_pct;
    this.video_views_to_50_pct = video_views_to_50_pct;
    this.video_views_to_75_pct = video_views_to_75_pct;
    this.video_views_to_100_pct = video_views_to_100_pct;
    this.contract_clicks = contract_clicks;
    this.contract_impressions = contract_impressions;
    this.contract_spend = contract_spend;
    this.contract_video_spend = contract_video_spend;
    this.contract_video_views = contract_video_views;
  }

  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call.
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return platform;
    case 1: return insertion_order_id;
    case 2: return line_item_id;
    case 3: return date;
    case 4: return platform_clicks;
    case 5: return platform_impressions;
    case 6: return platform_spend;
    case 7: return platform_video_spend;
    case 8: return platform_video_views;
    case 9: return video_views_3_sec;
    case 10: return video_views_10_sec;
    case 11: return video_views_30_sec;
    case 12: return video_views_to_25_pct;
    case 13: return video_views_to_50_pct;
    case 14: return video_views_to_75_pct;
    case 15: return video_views_to_100_pct;
    case 16: return contract_clicks;
    case 17: return contract_impressions;
    case 18: return contract_spend;
    case 19: return contract_video_spend;
    case 20: return contract_video_views;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  // Used by DatumReader.  Applications should not call.
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: platform = (java.lang.String)value$; break;
    case 1: insertion_order_id = (java.lang.Long)value$; break;
    case 2: line_item_id = (java.lang.Long)value$; break;
    case 3: date = (java.lang.String)value$; break;
    case 4: platform_clicks = (java.lang.Long)value$; break;
    case 5: platform_impressions = (java.lang.Long)value$; break;
    case 6: platform_spend = (java.lang.Float)value$; break;
    case 7: platform_video_spend = (java.lang.Float)value$; break;
    case 8: platform_video_views = (java.lang.Long)value$; break;
    case 9: video_views_3_sec = (java.lang.Long)value$; break;
    case 10: video_views_10_sec = (java.lang.Long)value$; break;
    case 11: video_views_30_sec = (java.lang.Long)value$; break;
    case 12: video_views_to_25_pct = (java.lang.Long)value$; break;
    case 13: video_views_to_50_pct = (java.lang.Long)value$; break;
    case 14: video_views_to_75_pct = (java.lang.Long)value$; break;
    case 15: video_views_to_100_pct = (java.lang.Long)value$; break;
    case 16: contract_clicks = (java.lang.Long)value$; break;
    case 17: contract_impressions = (java.lang.Long)value$; break;
    case 18: contract_spend = (java.lang.Float)value$; break;
    case 19: contract_video_spend = (java.lang.Float)value$; break;
    case 20: contract_video_views = (java.lang.Long)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  /**
   * Gets the value of the 'platform' field.
   * @return The value of the 'platform' field.
   */
  public java.lang.String getPlatform() {
    return platform;
  }

  /**
   * Sets the value of the 'platform' field.
   * @param value the value to set.
   */
  public void setPlatform(java.lang.String value) {
    this.platform = value;
  }

  /**
   * Gets the value of the 'insertion_order_id' field.
   * @return The value of the 'insertion_order_id' field.
   */
  public java.lang.Long getInsertionOrderId() {
    return insertion_order_id;
  }

  /**
   * Sets the value of the 'insertion_order_id' field.
   * @param value the value to set.
   */
  public void setInsertionOrderId(java.lang.Long value) {
    this.insertion_order_id = value;
  }

  /**
   * Gets the value of the 'line_item_id' field.
   * @return The value of the 'line_item_id' field.
   */
  public java.lang.Long getLineItemId() {
    return line_item_id;
  }

  /**
   * Sets the value of the 'line_item_id' field.
   * @param value the value to set.
   */
  public void setLineItemId(java.lang.Long value) {
    this.line_item_id = value;
  }

  /**
   * Gets the value of the 'date' field.
   * @return The value of the 'date' field.
   */
  public java.lang.String getDate() {
    return date;
  }

  /**
   * Sets the value of the 'date' field.
   * @param value the value to set.
   */
  public void setDate(java.lang.String value) {
    this.date = value;
  }

  /**
   * Gets the value of the 'platform_clicks' field.
   * @return The value of the 'platform_clicks' field.
   */
  public java.lang.Long getPlatformClicks() {
    return platform_clicks;
  }

  /**
   * Sets the value of the 'platform_clicks' field.
   * @param value the value to set.
   */
  public void setPlatformClicks(java.lang.Long value) {
    this.platform_clicks = value;
  }

  /**
   * Gets the value of the 'platform_impressions' field.
   * @return The value of the 'platform_impressions' field.
   */
  public java.lang.Long getPlatformImpressions() {
    return platform_impressions;
  }

  /**
   * Sets the value of the 'platform_impressions' field.
   * @param value the value to set.
   */
  public void setPlatformImpressions(java.lang.Long value) {
    this.platform_impressions = value;
  }

  /**
   * Gets the value of the 'platform_spend' field.
   * @return The value of the 'platform_spend' field.
   */
  public java.lang.Float getPlatformSpend() {
    return platform_spend;
  }

  /**
   * Sets the value of the 'platform_spend' field.
   * @param value the value to set.
   */
  public void setPlatformSpend(java.lang.Float value) {
    this.platform_spend = value;
  }

  /**
   * Gets the value of the 'platform_video_spend' field.
   * @return The value of the 'platform_video_spend' field.
   */
  public java.lang.Float getPlatformVideoSpend() {
    return platform_video_spend;
  }

  /**
   * Sets the value of the 'platform_video_spend' field.
   * @param value the value to set.
   */
  public void setPlatformVideoSpend(java.lang.Float value) {
    this.platform_video_spend = value;
  }

  /**
   * Gets the value of the 'platform_video_views' field.
   * @return The value of the 'platform_video_views' field.
   */
  public java.lang.Long getPlatformVideoViews() {
    return platform_video_views;
  }

  /**
   * Sets the value of the 'platform_video_views' field.
   * @param value the value to set.
   */
  public void setPlatformVideoViews(java.lang.Long value) {
    this.platform_video_views = value;
  }

  /**
   * Gets the value of the 'video_views_3_sec' field.
   * @return The value of the 'video_views_3_sec' field.
   */
  public java.lang.Long getVideoViews3Sec() {
    return video_views_3_sec;
  }

  /**
   * Sets the value of the 'video_views_3_sec' field.
   * @param value the value to set.
   */
  public void setVideoViews3Sec(java.lang.Long value) {
    this.video_views_3_sec = value;
  }

  /**
   * Gets the value of the 'video_views_10_sec' field.
   * @return The value of the 'video_views_10_sec' field.
   */
  public java.lang.Long getVideoViews10Sec() {
    return video_views_10_sec;
  }

  /**
   * Sets the value of the 'video_views_10_sec' field.
   * @param value the value to set.
   */
  public void setVideoViews10Sec(java.lang.Long value) {
    this.video_views_10_sec = value;
  }

  /**
   * Gets the value of the 'video_views_30_sec' field.
   * @return The value of the 'video_views_30_sec' field.
   */
  public java.lang.Long getVideoViews30Sec() {
    return video_views_30_sec;
  }

  /**
   * Sets the value of the 'video_views_30_sec' field.
   * @param value the value to set.
   */
  public void setVideoViews30Sec(java.lang.Long value) {
    this.video_views_30_sec = value;
  }

  /**
   * Gets the value of the 'video_views_to_25_pct' field.
   * @return The value of the 'video_views_to_25_pct' field.
   */
  public java.lang.Long getVideoViewsTo25Pct() {
    return video_views_to_25_pct;
  }

  /**
   * Sets the value of the 'video_views_to_25_pct' field.
   * @param value the value to set.
   */
  public void setVideoViewsTo25Pct(java.lang.Long value) {
    this.video_views_to_25_pct = value;
  }

  /**
   * Gets the value of the 'video_views_to_50_pct' field.
   * @return The value of the 'video_views_to_50_pct' field.
   */
  public java.lang.Long getVideoViewsTo50Pct() {
    return video_views_to_50_pct;
  }

  /**
   * Sets the value of the 'video_views_to_50_pct' field.
   * @param value the value to set.
   */
  public void setVideoViewsTo50Pct(java.lang.Long value) {
    this.video_views_to_50_pct = value;
  }

  /**
   * Gets the value of the 'video_views_to_75_pct' field.
   * @return The value of the 'video_views_to_75_pct' field.
   */
  public java.lang.Long getVideoViewsTo75Pct() {
    return video_views_to_75_pct;
  }

  /**
   * Sets the value of the 'video_views_to_75_pct' field.
   * @param value the value to set.
   */
  public void setVideoViewsTo75Pct(java.lang.Long value) {
    this.video_views_to_75_pct = value;
  }

  /**
   * Gets the value of the 'video_views_to_100_pct' field.
   * @return The value of the 'video_views_to_100_pct' field.
   */
  public java.lang.Long getVideoViewsTo100Pct() {
    return video_views_to_100_pct;
  }

  /**
   * Sets the value of the 'video_views_to_100_pct' field.
   * @param value the value to set.
   */
  public void setVideoViewsTo100Pct(java.lang.Long value) {
    this.video_views_to_100_pct = value;
  }

  /**
   * Gets the value of the 'contract_clicks' field.
   * @return The value of the 'contract_clicks' field.
   */
  public java.lang.Long getContractClicks() {
    return contract_clicks;
  }

  /**
   * Sets the value of the 'contract_clicks' field.
   * @param value the value to set.
   */
  public void setContractClicks(java.lang.Long value) {
    this.contract_clicks = value;
  }

  /**
   * Gets the value of the 'contract_impressions' field.
   * @return The value of the 'contract_impressions' field.
   */
  public java.lang.Long getContractImpressions() {
    return contract_impressions;
  }

  /**
   * Sets the value of the 'contract_impressions' field.
   * @param value the value to set.
   */
  public void setContractImpressions(java.lang.Long value) {
    this.contract_impressions = value;
  }

  /**
   * Gets the value of the 'contract_spend' field.
   * @return The value of the 'contract_spend' field.
   */
  public java.lang.Float getContractSpend() {
    return contract_spend;
  }

  /**
   * Sets the value of the 'contract_spend' field.
   * @param value the value to set.
   */
  public void setContractSpend(java.lang.Float value) {
    this.contract_spend = value;
  }

  /**
   * Gets the value of the 'contract_video_spend' field.
   * @return The value of the 'contract_video_spend' field.
   */
  public java.lang.Float getContractVideoSpend() {
    return contract_video_spend;
  }

  /**
   * Sets the value of the 'contract_video_spend' field.
   * @param value the value to set.
   */
  public void setContractVideoSpend(java.lang.Float value) {
    this.contract_video_spend = value;
  }

  /**
   * Gets the value of the 'contract_video_views' field.
   * @return The value of the 'contract_video_views' field.
   */
  public java.lang.Long getContractVideoViews() {
    return contract_video_views;
  }

  /**
   * Sets the value of the 'contract_video_views' field.
   * @param value the value to set.
   */
  public void setContractVideoViews(java.lang.Long value) {
    this.contract_video_views = value;
  }

  /**
   * Creates a new LineItemPlatformSummaryDaily RecordBuilder.
   * @return A new LineItemPlatformSummaryDaily RecordBuilder
   */
  public static com.pixability.model.LineItemPlatformSummaryDaily.Builder newBuilder() {
    return new com.pixability.model.LineItemPlatformSummaryDaily.Builder();
  }

  /**
   * Creates a new LineItemPlatformSummaryDaily RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new LineItemPlatformSummaryDaily RecordBuilder
   */
  public static com.pixability.model.LineItemPlatformSummaryDaily.Builder newBuilder(com.pixability.model.LineItemPlatformSummaryDaily.Builder other) {
    return new com.pixability.model.LineItemPlatformSummaryDaily.Builder(other);
  }

  /**
   * Creates a new LineItemPlatformSummaryDaily RecordBuilder by copying an existing LineItemPlatformSummaryDaily instance.
   * @param other The existing instance to copy.
   * @return A new LineItemPlatformSummaryDaily RecordBuilder
   */
  public static com.pixability.model.LineItemPlatformSummaryDaily.Builder newBuilder(com.pixability.model.LineItemPlatformSummaryDaily other) {
    return new com.pixability.model.LineItemPlatformSummaryDaily.Builder(other);
  }

  /**
   * RecordBuilder for LineItemPlatformSummaryDaily instances.
   */
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<LineItemPlatformSummaryDaily>
    implements org.apache.avro.data.RecordBuilder<LineItemPlatformSummaryDaily> {

    private java.lang.String platform;
    private long insertion_order_id;
    private long line_item_id;
    private java.lang.String date;
    private java.lang.Long platform_clicks;
    private java.lang.Long platform_impressions;
    private java.lang.Float platform_spend;
    private java.lang.Float platform_video_spend;
    private java.lang.Long platform_video_views;
    private java.lang.Long video_views_3_sec;
    private java.lang.Long video_views_10_sec;
    private java.lang.Long video_views_30_sec;
    private java.lang.Long video_views_to_25_pct;
    private java.lang.Long video_views_to_50_pct;
    private java.lang.Long video_views_to_75_pct;
    private java.lang.Long video_views_to_100_pct;
    private java.lang.Long contract_clicks;
    private java.lang.Long contract_impressions;
    private java.lang.Float contract_spend;
    private java.lang.Float contract_video_spend;
    private java.lang.Long contract_video_views;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(com.pixability.model.LineItemPlatformSummaryDaily.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.platform)) {
        this.platform = data().deepCopy(fields()[0].schema(), other.platform);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.insertion_order_id)) {
        this.insertion_order_id = data().deepCopy(fields()[1].schema(), other.insertion_order_id);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.line_item_id)) {
        this.line_item_id = data().deepCopy(fields()[2].schema(), other.line_item_id);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.date)) {
        this.date = data().deepCopy(fields()[3].schema(), other.date);
        fieldSetFlags()[3] = true;
      }
      if (isValidValue(fields()[4], other.platform_clicks)) {
        this.platform_clicks = data().deepCopy(fields()[4].schema(), other.platform_clicks);
        fieldSetFlags()[4] = true;
      }
      if (isValidValue(fields()[5], other.platform_impressions)) {
        this.platform_impressions = data().deepCopy(fields()[5].schema(), other.platform_impressions);
        fieldSetFlags()[5] = true;
      }
      if (isValidValue(fields()[6], other.platform_spend)) {
        this.platform_spend = data().deepCopy(fields()[6].schema(), other.platform_spend);
        fieldSetFlags()[6] = true;
      }
      if (isValidValue(fields()[7], other.platform_video_spend)) {
        this.platform_video_spend = data().deepCopy(fields()[7].schema(), other.platform_video_spend);
        fieldSetFlags()[7] = true;
      }
      if (isValidValue(fields()[8], other.platform_video_views)) {
        this.platform_video_views = data().deepCopy(fields()[8].schema(), other.platform_video_views);
        fieldSetFlags()[8] = true;
      }
      if (isValidValue(fields()[9], other.video_views_3_sec)) {
        this.video_views_3_sec = data().deepCopy(fields()[9].schema(), other.video_views_3_sec);
        fieldSetFlags()[9] = true;
      }
      if (isValidValue(fields()[10], other.video_views_10_sec)) {
        this.video_views_10_sec = data().deepCopy(fields()[10].schema(), other.video_views_10_sec);
        fieldSetFlags()[10] = true;
      }
      if (isValidValue(fields()[11], other.video_views_30_sec)) {
        this.video_views_30_sec = data().deepCopy(fields()[11].schema(), other.video_views_30_sec);
        fieldSetFlags()[11] = true;
      }
      if (isValidValue(fields()[12], other.video_views_to_25_pct)) {
        this.video_views_to_25_pct = data().deepCopy(fields()[12].schema(), other.video_views_to_25_pct);
        fieldSetFlags()[12] = true;
      }
      if (isValidValue(fields()[13], other.video_views_to_50_pct)) {
        this.video_views_to_50_pct = data().deepCopy(fields()[13].schema(), other.video_views_to_50_pct);
        fieldSetFlags()[13] = true;
      }
      if (isValidValue(fields()[14], other.video_views_to_75_pct)) {
        this.video_views_to_75_pct = data().deepCopy(fields()[14].schema(), other.video_views_to_75_pct);
        fieldSetFlags()[14] = true;
      }
      if (isValidValue(fields()[15], other.video_views_to_100_pct)) {
        this.video_views_to_100_pct = data().deepCopy(fields()[15].schema(), other.video_views_to_100_pct);
        fieldSetFlags()[15] = true;
      }
      if (isValidValue(fields()[16], other.contract_clicks)) {
        this.contract_clicks = data().deepCopy(fields()[16].schema(), other.contract_clicks);
        fieldSetFlags()[16] = true;
      }
      if (isValidValue(fields()[17], other.contract_impressions)) {
        this.contract_impressions = data().deepCopy(fields()[17].schema(), other.contract_impressions);
        fieldSetFlags()[17] = true;
      }
      if (isValidValue(fields()[18], other.contract_spend)) {
        this.contract_spend = data().deepCopy(fields()[18].schema(), other.contract_spend);
        fieldSetFlags()[18] = true;
      }
      if (isValidValue(fields()[19], other.contract_video_spend)) {
        this.contract_video_spend = data().deepCopy(fields()[19].schema(), other.contract_video_spend);
        fieldSetFlags()[19] = true;
      }
      if (isValidValue(fields()[20], other.contract_video_views)) {
        this.contract_video_views = data().deepCopy(fields()[20].schema(), other.contract_video_views);
        fieldSetFlags()[20] = true;
      }
    }

    /**
     * Creates a Builder by copying an existing LineItemPlatformSummaryDaily instance
     * @param other The existing instance to copy.
     */
    private Builder(com.pixability.model.LineItemPlatformSummaryDaily other) {
            super(SCHEMA$);
      if (isValidValue(fields()[0], other.platform)) {
        this.platform = data().deepCopy(fields()[0].schema(), other.platform);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.insertion_order_id)) {
        this.insertion_order_id = data().deepCopy(fields()[1].schema(), other.insertion_order_id);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.line_item_id)) {
        this.line_item_id = data().deepCopy(fields()[2].schema(), other.line_item_id);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.date)) {
        this.date = data().deepCopy(fields()[3].schema(), other.date);
        fieldSetFlags()[3] = true;
      }
      if (isValidValue(fields()[4], other.platform_clicks)) {
        this.platform_clicks = data().deepCopy(fields()[4].schema(), other.platform_clicks);
        fieldSetFlags()[4] = true;
      }
      if (isValidValue(fields()[5], other.platform_impressions)) {
        this.platform_impressions = data().deepCopy(fields()[5].schema(), other.platform_impressions);
        fieldSetFlags()[5] = true;
      }
      if (isValidValue(fields()[6], other.platform_spend)) {
        this.platform_spend = data().deepCopy(fields()[6].schema(), other.platform_spend);
        fieldSetFlags()[6] = true;
      }
      if (isValidValue(fields()[7], other.platform_video_spend)) {
        this.platform_video_spend = data().deepCopy(fields()[7].schema(), other.platform_video_spend);
        fieldSetFlags()[7] = true;
      }
      if (isValidValue(fields()[8], other.platform_video_views)) {
        this.platform_video_views = data().deepCopy(fields()[8].schema(), other.platform_video_views);
        fieldSetFlags()[8] = true;
      }
      if (isValidValue(fields()[9], other.video_views_3_sec)) {
        this.video_views_3_sec = data().deepCopy(fields()[9].schema(), other.video_views_3_sec);
        fieldSetFlags()[9] = true;
      }
      if (isValidValue(fields()[10], other.video_views_10_sec)) {
        this.video_views_10_sec = data().deepCopy(fields()[10].schema(), other.video_views_10_sec);
        fieldSetFlags()[10] = true;
      }
      if (isValidValue(fields()[11], other.video_views_30_sec)) {
        this.video_views_30_sec = data().deepCopy(fields()[11].schema(), other.video_views_30_sec);
        fieldSetFlags()[11] = true;
      }
      if (isValidValue(fields()[12], other.video_views_to_25_pct)) {
        this.video_views_to_25_pct = data().deepCopy(fields()[12].schema(), other.video_views_to_25_pct);
        fieldSetFlags()[12] = true;
      }
      if (isValidValue(fields()[13], other.video_views_to_50_pct)) {
        this.video_views_to_50_pct = data().deepCopy(fields()[13].schema(), other.video_views_to_50_pct);
        fieldSetFlags()[13] = true;
      }
      if (isValidValue(fields()[14], other.video_views_to_75_pct)) {
        this.video_views_to_75_pct = data().deepCopy(fields()[14].schema(), other.video_views_to_75_pct);
        fieldSetFlags()[14] = true;
      }
      if (isValidValue(fields()[15], other.video_views_to_100_pct)) {
        this.video_views_to_100_pct = data().deepCopy(fields()[15].schema(), other.video_views_to_100_pct);
        fieldSetFlags()[15] = true;
      }
      if (isValidValue(fields()[16], other.contract_clicks)) {
        this.contract_clicks = data().deepCopy(fields()[16].schema(), other.contract_clicks);
        fieldSetFlags()[16] = true;
      }
      if (isValidValue(fields()[17], other.contract_impressions)) {
        this.contract_impressions = data().deepCopy(fields()[17].schema(), other.contract_impressions);
        fieldSetFlags()[17] = true;
      }
      if (isValidValue(fields()[18], other.contract_spend)) {
        this.contract_spend = data().deepCopy(fields()[18].schema(), other.contract_spend);
        fieldSetFlags()[18] = true;
      }
      if (isValidValue(fields()[19], other.contract_video_spend)) {
        this.contract_video_spend = data().deepCopy(fields()[19].schema(), other.contract_video_spend);
        fieldSetFlags()[19] = true;
      }
      if (isValidValue(fields()[20], other.contract_video_views)) {
        this.contract_video_views = data().deepCopy(fields()[20].schema(), other.contract_video_views);
        fieldSetFlags()[20] = true;
      }
    }

    /**
      * Gets the value of the 'platform' field.
      * @return The value.
      */
    public java.lang.String getPlatform() {
      return platform;
    }

    /**
      * Sets the value of the 'platform' field.
      * @param value The value of 'platform'.
      * @return This builder.
      */
    public com.pixability.model.LineItemPlatformSummaryDaily.Builder setPlatform(java.lang.String value) {
      validate(fields()[0], value);
      this.platform = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'platform' field has been set.
      * @return True if the 'platform' field has been set, false otherwise.
      */
    public boolean hasPlatform() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'platform' field.
      * @return This builder.
      */
    public com.pixability.model.LineItemPlatformSummaryDaily.Builder clearPlatform() {
      platform = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'insertion_order_id' field.
      * @return The value.
      */
    public java.lang.Long getInsertionOrderId() {
      return insertion_order_id;
    }

    /**
      * Sets the value of the 'insertion_order_id' field.
      * @param value The value of 'insertion_order_id'.
      * @return This builder.
      */
    public com.pixability.model.LineItemPlatformSummaryDaily.Builder setInsertionOrderId(long value) {
      validate(fields()[1], value);
      this.insertion_order_id = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'insertion_order_id' field has been set.
      * @return True if the 'insertion_order_id' field has been set, false otherwise.
      */
    public boolean hasInsertionOrderId() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'insertion_order_id' field.
      * @return This builder.
      */
    public com.pixability.model.LineItemPlatformSummaryDaily.Builder clearInsertionOrderId() {
      fieldSetFlags()[1] = false;
      return this;
    }

    /**
      * Gets the value of the 'line_item_id' field.
      * @return The value.
      */
    public java.lang.Long getLineItemId() {
      return line_item_id;
    }

    /**
      * Sets the value of the 'line_item_id' field.
      * @param value The value of 'line_item_id'.
      * @return This builder.
      */
    public com.pixability.model.LineItemPlatformSummaryDaily.Builder setLineItemId(long value) {
      validate(fields()[2], value);
      this.line_item_id = value;
      fieldSetFlags()[2] = true;
      return this;
    }

    /**
      * Checks whether the 'line_item_id' field has been set.
      * @return True if the 'line_item_id' field has been set, false otherwise.
      */
    public boolean hasLineItemId() {
      return fieldSetFlags()[2];
    }


    /**
      * Clears the value of the 'line_item_id' field.
      * @return This builder.
      */
    public com.pixability.model.LineItemPlatformSummaryDaily.Builder clearLineItemId() {
      fieldSetFlags()[2] = false;
      return this;
    }

    /**
      * Gets the value of the 'date' field.
      * @return The value.
      */
    public java.lang.String getDate() {
      return date;
    }

    /**
      * Sets the value of the 'date' field.
      * @param value The value of 'date'.
      * @return This builder.
      */
    public com.pixability.model.LineItemPlatformSummaryDaily.Builder setDate(java.lang.String value) {
      validate(fields()[3], value);
      this.date = value;
      fieldSetFlags()[3] = true;
      return this;
    }

    /**
      * Checks whether the 'date' field has been set.
      * @return True if the 'date' field has been set, false otherwise.
      */
    public boolean hasDate() {
      return fieldSetFlags()[3];
    }


    /**
      * Clears the value of the 'date' field.
      * @return This builder.
      */
    public com.pixability.model.LineItemPlatformSummaryDaily.Builder clearDate() {
      date = null;
      fieldSetFlags()[3] = false;
      return this;
    }

    /**
      * Gets the value of the 'platform_clicks' field.
      * @return The value.
      */
    public java.lang.Long getPlatformClicks() {
      return platform_clicks;
    }

    /**
      * Sets the value of the 'platform_clicks' field.
      * @param value The value of 'platform_clicks'.
      * @return This builder.
      */
    public com.pixability.model.LineItemPlatformSummaryDaily.Builder setPlatformClicks(java.lang.Long value) {
      validate(fields()[4], value);
      this.platform_clicks = value;
      fieldSetFlags()[4] = true;
      return this;
    }

    /**
      * Checks whether the 'platform_clicks' field has been set.
      * @return True if the 'platform_clicks' field has been set, false otherwise.
      */
    public boolean hasPlatformClicks() {
      return fieldSetFlags()[4];
    }


    /**
      * Clears the value of the 'platform_clicks' field.
      * @return This builder.
      */
    public com.pixability.model.LineItemPlatformSummaryDaily.Builder clearPlatformClicks() {
      platform_clicks = null;
      fieldSetFlags()[4] = false;
      return this;
    }

    /**
      * Gets the value of the 'platform_impressions' field.
      * @return The value.
      */
    public java.lang.Long getPlatformImpressions() {
      return platform_impressions;
    }

    /**
      * Sets the value of the 'platform_impressions' field.
      * @param value The value of 'platform_impressions'.
      * @return This builder.
      */
    public com.pixability.model.LineItemPlatformSummaryDaily.Builder setPlatformImpressions(java.lang.Long value) {
      validate(fields()[5], value);
      this.platform_impressions = value;
      fieldSetFlags()[5] = true;
      return this;
    }

    /**
      * Checks whether the 'platform_impressions' field has been set.
      * @return True if the 'platform_impressions' field has been set, false otherwise.
      */
    public boolean hasPlatformImpressions() {
      return fieldSetFlags()[5];
    }


    /**
      * Clears the value of the 'platform_impressions' field.
      * @return This builder.
      */
    public com.pixability.model.LineItemPlatformSummaryDaily.Builder clearPlatformImpressions() {
      platform_impressions = null;
      fieldSetFlags()[5] = false;
      return this;
    }

    /**
      * Gets the value of the 'platform_spend' field.
      * @return The value.
      */
    public java.lang.Float getPlatformSpend() {
      return platform_spend;
    }

    /**
      * Sets the value of the 'platform_spend' field.
      * @param value The value of 'platform_spend'.
      * @return This builder.
      */
    public com.pixability.model.LineItemPlatformSummaryDaily.Builder setPlatformSpend(java.lang.Float value) {
      validate(fields()[6], value);
      this.platform_spend = value;
      fieldSetFlags()[6] = true;
      return this;
    }

    /**
      * Checks whether the 'platform_spend' field has been set.
      * @return True if the 'platform_spend' field has been set, false otherwise.
      */
    public boolean hasPlatformSpend() {
      return fieldSetFlags()[6];
    }


    /**
      * Clears the value of the 'platform_spend' field.
      * @return This builder.
      */
    public com.pixability.model.LineItemPlatformSummaryDaily.Builder clearPlatformSpend() {
      platform_spend = null;
      fieldSetFlags()[6] = false;
      return this;
    }

    /**
      * Gets the value of the 'platform_video_spend' field.
      * @return The value.
      */
    public java.lang.Float getPlatformVideoSpend() {
      return platform_video_spend;
    }

    /**
      * Sets the value of the 'platform_video_spend' field.
      * @param value The value of 'platform_video_spend'.
      * @return This builder.
      */
    public com.pixability.model.LineItemPlatformSummaryDaily.Builder setPlatformVideoSpend(java.lang.Float value) {
      validate(fields()[7], value);
      this.platform_video_spend = value;
      fieldSetFlags()[7] = true;
      return this;
    }

    /**
      * Checks whether the 'platform_video_spend' field has been set.
      * @return True if the 'platform_video_spend' field has been set, false otherwise.
      */
    public boolean hasPlatformVideoSpend() {
      return fieldSetFlags()[7];
    }


    /**
      * Clears the value of the 'platform_video_spend' field.
      * @return This builder.
      */
    public com.pixability.model.LineItemPlatformSummaryDaily.Builder clearPlatformVideoSpend() {
      platform_video_spend = null;
      fieldSetFlags()[7] = false;
      return this;
    }

    /**
      * Gets the value of the 'platform_video_views' field.
      * @return The value.
      */
    public java.lang.Long getPlatformVideoViews() {
      return platform_video_views;
    }

    /**
      * Sets the value of the 'platform_video_views' field.
      * @param value The value of 'platform_video_views'.
      * @return This builder.
      */
    public com.pixability.model.LineItemPlatformSummaryDaily.Builder setPlatformVideoViews(java.lang.Long value) {
      validate(fields()[8], value);
      this.platform_video_views = value;
      fieldSetFlags()[8] = true;
      return this;
    }

    /**
      * Checks whether the 'platform_video_views' field has been set.
      * @return True if the 'platform_video_views' field has been set, false otherwise.
      */
    public boolean hasPlatformVideoViews() {
      return fieldSetFlags()[8];
    }


    /**
      * Clears the value of the 'platform_video_views' field.
      * @return This builder.
      */
    public com.pixability.model.LineItemPlatformSummaryDaily.Builder clearPlatformVideoViews() {
      platform_video_views = null;
      fieldSetFlags()[8] = false;
      return this;
    }

    /**
      * Gets the value of the 'video_views_3_sec' field.
      * @return The value.
      */
    public java.lang.Long getVideoViews3Sec() {
      return video_views_3_sec;
    }

    /**
      * Sets the value of the 'video_views_3_sec' field.
      * @param value The value of 'video_views_3_sec'.
      * @return This builder.
      */
    public com.pixability.model.LineItemPlatformSummaryDaily.Builder setVideoViews3Sec(java.lang.Long value) {
      validate(fields()[9], value);
      this.video_views_3_sec = value;
      fieldSetFlags()[9] = true;
      return this;
    }

    /**
      * Checks whether the 'video_views_3_sec' field has been set.
      * @return True if the 'video_views_3_sec' field has been set, false otherwise.
      */
    public boolean hasVideoViews3Sec() {
      return fieldSetFlags()[9];
    }


    /**
      * Clears the value of the 'video_views_3_sec' field.
      * @return This builder.
      */
    public com.pixability.model.LineItemPlatformSummaryDaily.Builder clearVideoViews3Sec() {
      video_views_3_sec = null;
      fieldSetFlags()[9] = false;
      return this;
    }

    /**
      * Gets the value of the 'video_views_10_sec' field.
      * @return The value.
      */
    public java.lang.Long getVideoViews10Sec() {
      return video_views_10_sec;
    }

    /**
      * Sets the value of the 'video_views_10_sec' field.
      * @param value The value of 'video_views_10_sec'.
      * @return This builder.
      */
    public com.pixability.model.LineItemPlatformSummaryDaily.Builder setVideoViews10Sec(java.lang.Long value) {
      validate(fields()[10], value);
      this.video_views_10_sec = value;
      fieldSetFlags()[10] = true;
      return this;
    }

    /**
      * Checks whether the 'video_views_10_sec' field has been set.
      * @return True if the 'video_views_10_sec' field has been set, false otherwise.
      */
    public boolean hasVideoViews10Sec() {
      return fieldSetFlags()[10];
    }


    /**
      * Clears the value of the 'video_views_10_sec' field.
      * @return This builder.
      */
    public com.pixability.model.LineItemPlatformSummaryDaily.Builder clearVideoViews10Sec() {
      video_views_10_sec = null;
      fieldSetFlags()[10] = false;
      return this;
    }

    /**
      * Gets the value of the 'video_views_30_sec' field.
      * @return The value.
      */
    public java.lang.Long getVideoViews30Sec() {
      return video_views_30_sec;
    }

    /**
      * Sets the value of the 'video_views_30_sec' field.
      * @param value The value of 'video_views_30_sec'.
      * @return This builder.
      */
    public com.pixability.model.LineItemPlatformSummaryDaily.Builder setVideoViews30Sec(java.lang.Long value) {
      validate(fields()[11], value);
      this.video_views_30_sec = value;
      fieldSetFlags()[11] = true;
      return this;
    }

    /**
      * Checks whether the 'video_views_30_sec' field has been set.
      * @return True if the 'video_views_30_sec' field has been set, false otherwise.
      */
    public boolean hasVideoViews30Sec() {
      return fieldSetFlags()[11];
    }


    /**
      * Clears the value of the 'video_views_30_sec' field.
      * @return This builder.
      */
    public com.pixability.model.LineItemPlatformSummaryDaily.Builder clearVideoViews30Sec() {
      video_views_30_sec = null;
      fieldSetFlags()[11] = false;
      return this;
    }

    /**
      * Gets the value of the 'video_views_to_25_pct' field.
      * @return The value.
      */
    public java.lang.Long getVideoViewsTo25Pct() {
      return video_views_to_25_pct;
    }

    /**
      * Sets the value of the 'video_views_to_25_pct' field.
      * @param value The value of 'video_views_to_25_pct'.
      * @return This builder.
      */
    public com.pixability.model.LineItemPlatformSummaryDaily.Builder setVideoViewsTo25Pct(java.lang.Long value) {
      validate(fields()[12], value);
      this.video_views_to_25_pct = value;
      fieldSetFlags()[12] = true;
      return this;
    }

    /**
      * Checks whether the 'video_views_to_25_pct' field has been set.
      * @return True if the 'video_views_to_25_pct' field has been set, false otherwise.
      */
    public boolean hasVideoViewsTo25Pct() {
      return fieldSetFlags()[12];
    }


    /**
      * Clears the value of the 'video_views_to_25_pct' field.
      * @return This builder.
      */
    public com.pixability.model.LineItemPlatformSummaryDaily.Builder clearVideoViewsTo25Pct() {
      video_views_to_25_pct = null;
      fieldSetFlags()[12] = false;
      return this;
    }

    /**
      * Gets the value of the 'video_views_to_50_pct' field.
      * @return The value.
      */
    public java.lang.Long getVideoViewsTo50Pct() {
      return video_views_to_50_pct;
    }

    /**
      * Sets the value of the 'video_views_to_50_pct' field.
      * @param value The value of 'video_views_to_50_pct'.
      * @return This builder.
      */
    public com.pixability.model.LineItemPlatformSummaryDaily.Builder setVideoViewsTo50Pct(java.lang.Long value) {
      validate(fields()[13], value);
      this.video_views_to_50_pct = value;
      fieldSetFlags()[13] = true;
      return this;
    }

    /**
      * Checks whether the 'video_views_to_50_pct' field has been set.
      * @return True if the 'video_views_to_50_pct' field has been set, false otherwise.
      */
    public boolean hasVideoViewsTo50Pct() {
      return fieldSetFlags()[13];
    }


    /**
      * Clears the value of the 'video_views_to_50_pct' field.
      * @return This builder.
      */
    public com.pixability.model.LineItemPlatformSummaryDaily.Builder clearVideoViewsTo50Pct() {
      video_views_to_50_pct = null;
      fieldSetFlags()[13] = false;
      return this;
    }

    /**
      * Gets the value of the 'video_views_to_75_pct' field.
      * @return The value.
      */
    public java.lang.Long getVideoViewsTo75Pct() {
      return video_views_to_75_pct;
    }

    /**
      * Sets the value of the 'video_views_to_75_pct' field.
      * @param value The value of 'video_views_to_75_pct'.
      * @return This builder.
      */
    public com.pixability.model.LineItemPlatformSummaryDaily.Builder setVideoViewsTo75Pct(java.lang.Long value) {
      validate(fields()[14], value);
      this.video_views_to_75_pct = value;
      fieldSetFlags()[14] = true;
      return this;
    }

    /**
      * Checks whether the 'video_views_to_75_pct' field has been set.
      * @return True if the 'video_views_to_75_pct' field has been set, false otherwise.
      */
    public boolean hasVideoViewsTo75Pct() {
      return fieldSetFlags()[14];
    }


    /**
      * Clears the value of the 'video_views_to_75_pct' field.
      * @return This builder.
      */
    public com.pixability.model.LineItemPlatformSummaryDaily.Builder clearVideoViewsTo75Pct() {
      video_views_to_75_pct = null;
      fieldSetFlags()[14] = false;
      return this;
    }

    /**
      * Gets the value of the 'video_views_to_100_pct' field.
      * @return The value.
      */
    public java.lang.Long getVideoViewsTo100Pct() {
      return video_views_to_100_pct;
    }

    /**
      * Sets the value of the 'video_views_to_100_pct' field.
      * @param value The value of 'video_views_to_100_pct'.
      * @return This builder.
      */
    public com.pixability.model.LineItemPlatformSummaryDaily.Builder setVideoViewsTo100Pct(java.lang.Long value) {
      validate(fields()[15], value);
      this.video_views_to_100_pct = value;
      fieldSetFlags()[15] = true;
      return this;
    }

    /**
      * Checks whether the 'video_views_to_100_pct' field has been set.
      * @return True if the 'video_views_to_100_pct' field has been set, false otherwise.
      */
    public boolean hasVideoViewsTo100Pct() {
      return fieldSetFlags()[15];
    }


    /**
      * Clears the value of the 'video_views_to_100_pct' field.
      * @return This builder.
      */
    public com.pixability.model.LineItemPlatformSummaryDaily.Builder clearVideoViewsTo100Pct() {
      video_views_to_100_pct = null;
      fieldSetFlags()[15] = false;
      return this;
    }

    /**
      * Gets the value of the 'contract_clicks' field.
      * @return The value.
      */
    public java.lang.Long getContractClicks() {
      return contract_clicks;
    }

    /**
      * Sets the value of the 'contract_clicks' field.
      * @param value The value of 'contract_clicks'.
      * @return This builder.
      */
    public com.pixability.model.LineItemPlatformSummaryDaily.Builder setContractClicks(java.lang.Long value) {
      validate(fields()[16], value);
      this.contract_clicks = value;
      fieldSetFlags()[16] = true;
      return this;
    }

    /**
      * Checks whether the 'contract_clicks' field has been set.
      * @return True if the 'contract_clicks' field has been set, false otherwise.
      */
    public boolean hasContractClicks() {
      return fieldSetFlags()[16];
    }


    /**
      * Clears the value of the 'contract_clicks' field.
      * @return This builder.
      */
    public com.pixability.model.LineItemPlatformSummaryDaily.Builder clearContractClicks() {
      contract_clicks = null;
      fieldSetFlags()[16] = false;
      return this;
    }

    /**
      * Gets the value of the 'contract_impressions' field.
      * @return The value.
      */
    public java.lang.Long getContractImpressions() {
      return contract_impressions;
    }

    /**
      * Sets the value of the 'contract_impressions' field.
      * @param value The value of 'contract_impressions'.
      * @return This builder.
      */
    public com.pixability.model.LineItemPlatformSummaryDaily.Builder setContractImpressions(java.lang.Long value) {
      validate(fields()[17], value);
      this.contract_impressions = value;
      fieldSetFlags()[17] = true;
      return this;
    }

    /**
      * Checks whether the 'contract_impressions' field has been set.
      * @return True if the 'contract_impressions' field has been set, false otherwise.
      */
    public boolean hasContractImpressions() {
      return fieldSetFlags()[17];
    }


    /**
      * Clears the value of the 'contract_impressions' field.
      * @return This builder.
      */
    public com.pixability.model.LineItemPlatformSummaryDaily.Builder clearContractImpressions() {
      contract_impressions = null;
      fieldSetFlags()[17] = false;
      return this;
    }

    /**
      * Gets the value of the 'contract_spend' field.
      * @return The value.
      */
    public java.lang.Float getContractSpend() {
      return contract_spend;
    }

    /**
      * Sets the value of the 'contract_spend' field.
      * @param value The value of 'contract_spend'.
      * @return This builder.
      */
    public com.pixability.model.LineItemPlatformSummaryDaily.Builder setContractSpend(java.lang.Float value) {
      validate(fields()[18], value);
      this.contract_spend = value;
      fieldSetFlags()[18] = true;
      return this;
    }

    /**
      * Checks whether the 'contract_spend' field has been set.
      * @return True if the 'contract_spend' field has been set, false otherwise.
      */
    public boolean hasContractSpend() {
      return fieldSetFlags()[18];
    }


    /**
      * Clears the value of the 'contract_spend' field.
      * @return This builder.
      */
    public com.pixability.model.LineItemPlatformSummaryDaily.Builder clearContractSpend() {
      contract_spend = null;
      fieldSetFlags()[18] = false;
      return this;
    }

    /**
      * Gets the value of the 'contract_video_spend' field.
      * @return The value.
      */
    public java.lang.Float getContractVideoSpend() {
      return contract_video_spend;
    }

    /**
      * Sets the value of the 'contract_video_spend' field.
      * @param value The value of 'contract_video_spend'.
      * @return This builder.
      */
    public com.pixability.model.LineItemPlatformSummaryDaily.Builder setContractVideoSpend(java.lang.Float value) {
      validate(fields()[19], value);
      this.contract_video_spend = value;
      fieldSetFlags()[19] = true;
      return this;
    }

    /**
      * Checks whether the 'contract_video_spend' field has been set.
      * @return True if the 'contract_video_spend' field has been set, false otherwise.
      */
    public boolean hasContractVideoSpend() {
      return fieldSetFlags()[19];
    }


    /**
      * Clears the value of the 'contract_video_spend' field.
      * @return This builder.
      */
    public com.pixability.model.LineItemPlatformSummaryDaily.Builder clearContractVideoSpend() {
      contract_video_spend = null;
      fieldSetFlags()[19] = false;
      return this;
    }

    /**
      * Gets the value of the 'contract_video_views' field.
      * @return The value.
      */
    public java.lang.Long getContractVideoViews() {
      return contract_video_views;
    }

    /**
      * Sets the value of the 'contract_video_views' field.
      * @param value The value of 'contract_video_views'.
      * @return This builder.
      */
    public com.pixability.model.LineItemPlatformSummaryDaily.Builder setContractVideoViews(java.lang.Long value) {
      validate(fields()[20], value);
      this.contract_video_views = value;
      fieldSetFlags()[20] = true;
      return this;
    }

    /**
      * Checks whether the 'contract_video_views' field has been set.
      * @return True if the 'contract_video_views' field has been set, false otherwise.
      */
    public boolean hasContractVideoViews() {
      return fieldSetFlags()[20];
    }


    /**
      * Clears the value of the 'contract_video_views' field.
      * @return This builder.
      */
    public com.pixability.model.LineItemPlatformSummaryDaily.Builder clearContractVideoViews() {
      contract_video_views = null;
      fieldSetFlags()[20] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public LineItemPlatformSummaryDaily build() {
      try {
        LineItemPlatformSummaryDaily record = new LineItemPlatformSummaryDaily();
        record.platform = fieldSetFlags()[0] ? this.platform : (java.lang.String) defaultValue(fields()[0]);
        record.insertion_order_id = fieldSetFlags()[1] ? this.insertion_order_id : (java.lang.Long) defaultValue(fields()[1]);
        record.line_item_id = fieldSetFlags()[2] ? this.line_item_id : (java.lang.Long) defaultValue(fields()[2]);
        record.date = fieldSetFlags()[3] ? this.date : (java.lang.String) defaultValue(fields()[3]);
        record.platform_clicks = fieldSetFlags()[4] ? this.platform_clicks : (java.lang.Long) defaultValue(fields()[4]);
        record.platform_impressions = fieldSetFlags()[5] ? this.platform_impressions : (java.lang.Long) defaultValue(fields()[5]);
        record.platform_spend = fieldSetFlags()[6] ? this.platform_spend : (java.lang.Float) defaultValue(fields()[6]);
        record.platform_video_spend = fieldSetFlags()[7] ? this.platform_video_spend : (java.lang.Float) defaultValue(fields()[7]);
        record.platform_video_views = fieldSetFlags()[8] ? this.platform_video_views : (java.lang.Long) defaultValue(fields()[8]);
        record.video_views_3_sec = fieldSetFlags()[9] ? this.video_views_3_sec : (java.lang.Long) defaultValue(fields()[9]);
        record.video_views_10_sec = fieldSetFlags()[10] ? this.video_views_10_sec : (java.lang.Long) defaultValue(fields()[10]);
        record.video_views_30_sec = fieldSetFlags()[11] ? this.video_views_30_sec : (java.lang.Long) defaultValue(fields()[11]);
        record.video_views_to_25_pct = fieldSetFlags()[12] ? this.video_views_to_25_pct : (java.lang.Long) defaultValue(fields()[12]);
        record.video_views_to_50_pct = fieldSetFlags()[13] ? this.video_views_to_50_pct : (java.lang.Long) defaultValue(fields()[13]);
        record.video_views_to_75_pct = fieldSetFlags()[14] ? this.video_views_to_75_pct : (java.lang.Long) defaultValue(fields()[14]);
        record.video_views_to_100_pct = fieldSetFlags()[15] ? this.video_views_to_100_pct : (java.lang.Long) defaultValue(fields()[15]);
        record.contract_clicks = fieldSetFlags()[16] ? this.contract_clicks : (java.lang.Long) defaultValue(fields()[16]);
        record.contract_impressions = fieldSetFlags()[17] ? this.contract_impressions : (java.lang.Long) defaultValue(fields()[17]);
        record.contract_spend = fieldSetFlags()[18] ? this.contract_spend : (java.lang.Float) defaultValue(fields()[18]);
        record.contract_video_spend = fieldSetFlags()[19] ? this.contract_video_spend : (java.lang.Float) defaultValue(fields()[19]);
        record.contract_video_views = fieldSetFlags()[20] ? this.contract_video_views : (java.lang.Long) defaultValue(fields()[20]);
        return record;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<LineItemPlatformSummaryDaily>
    WRITER$ = (org.apache.avro.io.DatumWriter<LineItemPlatformSummaryDaily>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<LineItemPlatformSummaryDaily>
    READER$ = (org.apache.avro.io.DatumReader<LineItemPlatformSummaryDaily>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

}
